name: test
description: 'Analysis project'
inputs:
  profile:
    description: 'Build profile'
    required: true
  version:
    description: 'Project version'
    required: true
  semanticVersion:
    description: 'Project semantic version'
    required: true
  hashVersion:
    description: 'Project hash commit'
    required: true
  branch:
    description: 'Git branch'
    required: true
  githubToken:
    description: 'GitHub Token'
    required: true
  sonarToken:
    description: 'Sonar Token'
    required: true
  skipSonar:
    description: 'Skip sonar scanner'
    required: true
    default: 'false'
  javaDist:
    description: 'Java distribution'
    required: true
    default: 'temurin'
  javaVersion:
    description: 'Java version'
    required: true
    default: '11'

runs:
  using: 'composite'
  steps:
    - uses: actions/setup-java@v2
      with:
        distribution: ${{ inputs.javaDist }}
        java-version: ${{ inputs.javaVersion }}
        cache: 'gradle'

    - name: Cache SonarCloud packages
      uses: actions/cache@v2.1.4
      if: inputs.skipSonar == 'false'
      with:
        path: ~/.sonar/cache
        key: ${{ runner.os }}-sonar
        restore-keys: ${{ runner.os }}-sonar

    - name: Generate jOOQ test schema
      shell: bash
      run: ./generateJooq.sh

    - name: Full test
      shell: bash
      run: ./gradlew test -Pprofile=${{ inputs.profile }} -PsemanticVersion=${{ inputs.semanticVersion }} --stacktrace

    - name: SonarQube
      shell: bash
      if: inputs.skipSonar == 'false'
      run: |
        ./gradlew sonarqube -x test --stacktrace \
            -Pprofile=${{ inputs.profile }} \
            -PsemanticVersion=${{ inputs.semanticVersion }} \
            -Dsonar.login=${{ inputs.sonarToken }} -Dsonar.branch.name=${{ inputs.branch }} \
            -Dorg.gradle.jvmargs="-Xmx2g -XX:MaxMetaspaceSize=512m -XX:+HeapDumpOnOutOfMemoryError"
      env:
        GITHUB_TOKEN: ${{ inputs.githubToken }}
