/*
 * This file was generated by the Gradle 'init' task.
 *
 * The settings file is used to specify which projects to include in your build.
 *
 * Detailed information about configuring a multi-project build in Gradle can be found
 * in the user manual at https://docs.gradle.org/6.7/userguide/multi_project_builds.html
 */

pluginManagement {
    repositories {
        mavenLocal()
        gradlePluginPortal()
    }
}

rootProject.name = "jooqx"
val profile: String by settings
val pools = mapOf(
    "jpa" to arrayOf(":jpa-ext"),
    "jooqx" to arrayOf(":jooqx-core", ":spi"),
    "sample" to arrayOf(":sample:model"),
    "rsql" to arrayOf(":rsql:core", ":rsql:jooq"),
    "integtest" to arrayOf(":integtest")
)

var pp: Array<String> = arrayOf()

if (profile == "jpa") {
    pp = pools["jpa"]!!
}

if (profile == "analysis") {
    val excludes = arrayOf<String>()
    pp = pools.values.toTypedArray().flatten().filter { !excludes.contains(it) }.toTypedArray()
}

if (profile == "rsql") {
    pp = pools["jpa"]!! + pools["rsql"]!!
}

if (profile == "build") {
    val excludes = pools["sample"]!! + pools["integtest"]!!
    pp = pools.values.toTypedArray().flatten().filter { !excludes.contains(it) }.toTypedArray()
}

if (pp.isEmpty()) {
    pp = pools.values.toTypedArray().flatten().toTypedArray()
}

pp.forEach { include(it) }
if (pp.contains(":jooqx-core")) {
    project(":jooqx-core").projectDir = file("core")
}
