[versions]
pluginPlayio = "0.3.0"
pluginJooq = "5.2"
## JUnit
junit5 = "5.10.2"
junit5Vertx = "4.2.5"
junit5Container = "1.19.7"
junitPioneer_jdk8 = "1.9.1"
junitPioneer_jdk11 = "2.2.0"
## Logging
slf4j = "2.0.12"
log4j2 = "2.23.1"
logback = "1.3.14"
## Jackson
jackson = "2.17.0"

[libraries]
jetbrainsAnnotations = { module = "org.jetbrains:annotations", version = "24.1.0" }
## Junit5
junit5Api = { module = "org.junit.jupiter:junit-jupiter-api", version.ref = "junit5" }
junit5Engine = { module = "org.junit.jupiter:junit-jupiter-engine", version.ref = "junit5" }
junit5Vintage = { module = "org.junit.vintage:junit-vintage-engine", version.ref = "junit5" }
junit5Params = { module = "org.junit.jupiter:junit-jupiter-params", version.ref = "junit5" }
junit5Vertx = { module = "io.vertx:vertx-junit5", version.ref = "junit5Vertx" }
junitPioneer_jdk8 = { module = "org.junit-pioneer:junit-pioneer", version.ref = "junitPioneer_jdk8" }
junitPioneer_jdk11 = { module = "org.junit-pioneer:junit-pioneer", version.ref = "junitPioneer_jdk11" }
## Jackson
jacksonDatabind = { module = "com.fasterxml.jackson.core:jackson-databind", version.ref = "jackson" }
jacksonDatetime = { module = "com.fasterxml.jackson.datatype:jackson-datatype-jsr310", version.ref = "jackson" }
## TestContainer
junit5Container = { module = "org.testcontainers:junit-jupiter", version.ref = "junit5Container" }
postgresContainer = { module = "org.testcontainers:postgresql", version.ref = "junit5Container" }
mysqlContainer = { module = "org.testcontainers:mysql", version.ref = "junit5Container" }
## log4j2
log4j2Api = { module = "org.apache.logging.log4j:log4j-api", version.ref = "log4j2" }
log4j2Core = { module = "org.apache.logging.log4j:log4j-core", version.ref = "log4j2" }
log4j2slf4j = { module = "org.apache.logging.log4j:log4j-slf4j-impl", version.ref = "log4j2" }
## slf4j
slf4j = { module = "org.slf4j:slf4j-api", version.ref = "slf4j" }
slf4jSimple = { module = "org.slf4j:slf4j-simple", version.ref = "slf4j" }
logback = { module = "ch.qos.logback:logback-classic", version.ref = "logback" }

[bundles]
junit5 = ["junit5Api", "junit5Engine", "junit5Params"]
log4j2 = ["log4j2Api", "log4j2Core", "log4j2slf4j"]
logback = ["slf4j", "logback"]
slf4jImpl = ["slf4j", "slf4jSimple"]

[plugins]
oss = { id = "cloud.playio.gradle.oss", version.ref = "pluginPlayio" }
root = { id = "cloud.playio.gradle.root", version.ref = "pluginPlayio" }
antora = { id = "cloud.playio.gradle.antora", version.ref = "pluginPlayio" }
pandoc = { id = "cloud.playio.gradle.pandoc", version.ref = "pluginPlayio" }
docgen = { id = "cloud.playio.gradle.docgen", version.ref = "pluginPlayio" }
codegen = { id = "cloud.playio.gradle.codegen", version.ref = "pluginPlayio" }
jooq = { id = "nu.studer.jooq", version.ref = "pluginJooq" }
