name: build
description: 'Build project'
inputs:
  profile:
    description: 'Build profile'
    required: true
  version:
    description: 'Project version'
    required: true
  semanticVersion:
    description: 'Project semantic version'
    required: true
  hashVersion:
    description: 'Project hash commit'
    required: true
  javaDist:
    description: 'Java distribution'
    required: true
    default: 'temurin'
  javaVersion:
    description: 'Java version'
    required: true
    default: '11'

runs:
  using: 'composite'
  steps:
    - uses: actions/setup-java@v3.9.0
      with:
        distribution: ${{ inputs.javaDist }}
        java-version: ${{ inputs.javaVersion }}
        cache: 'gradle'

    - name: Build
      shell: bash
      run: |
        ./gradlew clean build -x test \
            -Pprofile=${{ inputs.profile }} \
            -Pversion=${{ inputs.version }} \
            -PsemanticVersion=${{ inputs.semanticVersion }} \
            -PbuildBy="GitHub-Action" \
            -PbuildHash=${{ inputs.hashVersion }} \
            --no-daemon
