name: build
description: 'Build project'
inputs:
  profile:
    description: 'Build profile'
    required: true
  version:
    description: 'Project version'
    required: true
  semanticVersion:
    description: 'Project semantic version'
    required: true
  hashVersion:
    description: 'Project hash commit'
    required: true
  shouldPublish:
    description: 'Should Publish to remote repository'
    required: true
    default: 'true'
  isRelease:
    description: 'Should Publish'
    required: true
    default: 'false'
  ossrh-user:
    description: 'OSSRH User'
    required: true
  ossrh-token:
    description: 'OSSRH Token'
    required: true

runs:
  using: 'composite'
  steps:
    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        distribution: microsoft
        java-version: 11

    - name: Cache Gradle packages
      uses: actions/cache@v2.1.4
      with:
        path: ~/.gradle/caches
        key: ${{ runner.os }}-gradle-build-${{ hashFiles('**/*.gradle.kts') }}
        restore-keys: ${{ runner.os }}-gradle-build

    - name: Build
      shell: bash
      run: |
        ./gradlew clean build -x test \
                        -Pprofile=${{ inputs.profile }} \
                        -Pversion=${{ inputs.version }} \
                        -PsemanticVersion=${{ inputs.semanticVersion }} \
                        -PbuildBy="GitHub Action" -PbuildHash=${{ inputs.hashVersion }}

    #    - name: Publish GitHub Package
    #      if: inputs.isRelease == 'true' && env.ENABLE_GH_MAVEN == 'true'
    #      run: |
    #        args=( -Psigning.gnupg.homeDir=/home/runner/.gnupg \
    #               -Psigning.gnupg.keyName=${{ steps.import_gpg.outputs.keyid }} \
    #               -Psigning.gnupg.passphrase=${{ secrets.CI_GPG_PASSPHARSE }} \
    #               -Pnexus.username=${{ github.repository_owner }} \
    #               -Pnexus.password=${{ secrets.OSS_GITHUB_TOKEN }} )
    #        args+=( -Pgithub )
    #        [[ "${{ inputs.isRelease }}" == 'true' ]] && args+=( -Prelease )
    #        ./gradlew publish "${args[@]}"

    - name: Publish Sonatype OSSRH
      shell: bash
      if: inputs.shouldPublish == 'true' && inputs.isRelease != 'true'
      run: |
        args=( -Pversion=${{ inputs.version }} \
               -PsemanticVersion=${{ inputs.semanticVersion }} \
               -Pnexus.username=${{ inputs.ossrh-user }} \
               -Pnexus.password=${{ inputs.ossrh-token }} )
        ./gradlew publish "${args[@]}"
