= Use jOOQ.x in your project
:navtitle: Usage

To use `jooqx` add the following https://search.maven.org/artifact/io.github.zero88/jooqx/{jooqx-version}/jar[dependency]
to the `dependencies` section of your build descriptor:

== Maven

In your `pom.xml`,

[source,xml,subs="attributes,verbatim"]
----
<dependencies>
    <dependency>
        <groupId>org.jooq</groupId>
        <artifactId>jooq</artifactId>
        <version>{jooq-version}</version>
    </dependency>
    <dependency>
        <groupId>io.vertx</groupId>
        <artifactId>vertx-core</artifactId>
        <version>{vertx-version}</version>
    </dependency>
    <dependency>
        <groupId>io.github.zero88</groupId>
        <artifactId>jooqx</artifactId>
        <version>{jooqx-version}</version>
    </dependency>
    <!-- For some SPI includes specific converter based on Vert.x database client -->
    <dependency>
        <groupId>io.github.zero88</groupId>
        <artifactId>jooqx-spi</artifactId>
        <version>{jooqx-version}</version>
    </dependency>
</dependencies>
----

== Gradle

In your `build.gradle`,

[source,groovy,subs="attributes,verbatim"]
----
dependencies {
    api("org.jooq:jooq:{jooqx-version}")
    api("io.vertx:vertx-core:{vertx-version}")
    api("io.github.zero88:jooqx:{jooqx-version}")
    // For some SPI includes specific converter based on Vert.x database client
    api("io.github.zero88:jooqx-spi:{jooqx-version}")
}
----

== Remarks

:icons: font
[TIP]
.`jooqx` is only depended on 2 main libraries
====
- `io.vertx:vertx-core`
- `org.jooq:jooq`
====

Adding this `jooqx` library JAR will not automatically add a `database driver` JAR to your project. You should ensure that your project also has a suitable `database driver` as a dependency.

For example:

* With `legacy JDBC` and connecting to `MySQL` driver

[source,groovy,subs="attributes,verbatim"]
----
dependencies {
    api("mysql:mysql-connector-java:8.0.23")
    // It is recommendation to use HikariCP instead of c3p0
    api("com.zaxxer:HikariCP:4.0.2")
    api("io.vertx:vertx-jdbc-client:{vertx-version}") {
        exclude("com.mchange")
    }
    api("io.github.zero88:jooqx:{jooqx-version}")
}
----

* With `reactive PostgreSQL` client

[source,groovy,subs="attributes,verbatim"]
----
dependencies {
    api("io.vertx:vertx-pg-client:{vertx-version}")
    api("io.github.zero88:jooqx:{jooqx-version}")
}
----

* With `reactive JDBC` client and `H2`

[source,groovy,subs="attributes,verbatim"]
----
dependencies {
    api("com.h2database:h2:1.4.200")
    // Agroal pool - Default in Vertx SQL client - Not yet has alternatives
    api("io.agroal:agroal-pool:1.9")
    api("io.vertx:vertx-sql-client:{vertx-version}")
    api("io.github.zero88:jooqx:{jooqx-version}")
}
----

== Reactive version

Reference to xref:features-rxify.adoc[reactive version] for more detail.

== Logging

`jooq.x` reuses the Vert.x logging mechanism. Please, refers to https://vertx.io/docs/vertx-core/java/#_logging

So in short, you can use `slf4j`, `log4j2`, or `jdk logging` by simple below configuration before start your application. Remember add your flavor log library in your classpath.

[source,java]
----
// for slf4j
System.setProperty("vertx.logger-delegate-factory-class-name", "io.vertx.core.logging.SLF4JLogDelegateFactory");

// for log4j2
System.setProperty("vertx.logger-delegate-factory-class-name", "io.vertx.core.logging.Log4j2LogDelegateFactory");

// fallback to jdk logging or config explicitly
System.setProperty("vertx.logger-delegate-factory-class-name", "io.vertx.core.logging.JULLogDelegateFactory");
----

*Note*

`jOOQ` use `slf4j` by default, so in case your application is using `log4j2`, please add https://central.sonatype.com/artifact/org.apache.logging.log4j/log4j-slf4j-impl/2.20.0/versions[`log4j-slf4j-impl`] into the application classpath to redirect jOOQ log by `slf4j` to `log4j2`.
