== Changelog

=== https://github.com/zero88/jooqx/tree/v2.0.0-rc3[v2.0.0-rc3] (2024-06-22)

https://github.com/zero88/jooqx/compare/docs/jooqx/v2.0.0-rc2+2...v2.0.0-rc3[Full
Changelog]

*Implemented enhancements:*

* Make java17 is the baseline
https://github.com/zero88/jooqx/issues/216[#216]

*Merged pull requests:*

* Append jvm variant as build version to support multiple java versions
https://github.com/zero88/jooqx/pull/252[#252]
(https://github.com/zero88[zero88])
* Release v2.0.0-rc2+2 https://github.com/zero88/jooqx/pull/251[#251]
(https://github.com/zero88[zero88])
* feat(gha): Tweak a step to make jooqx support multiple java versions
https://github.com/zero88/jooqx/pull/250[#250]
(https://github.com/zero88[zero88])
* Release v2.0.0-rc2 https://github.com/zero88/jooqx/pull/249[#249]
(https://github.com/zero88[zero88])
* feat(gradle): Tweak a step to make jooqx support multiple java
versions https://github.com/zero88/jooqx/pull/248[#248]
(https://github.com/zero88[zero88])
* fix(DataTypeMapper): support jooq version >= 3.18
https://github.com/zero88/jooqx/pull/243[#243]
(https://github.com/zero88[zero88])
* fix(deps): update jooq.jdk17 to v3.19.10 (patch)
https://github.com/zero88/jooqx/pull/240[#240]
(https://github.com/apps/renovate[renovate[bot]])
* fix(deps): update dependency org.hsqldb:hsqldb to v2.7.3
https://github.com/zero88/jooqx/pull/239[#239]
(https://github.com/apps/renovate[renovate[bot]])
* chore(renovate): add renovate for sdkman
https://github.com/zero88/jooqx/pull/236[#236]
(https://github.com/zero88[zero88])
* fix(deps): update dependency org.xerial:sqlite-jdbc to v3.46.0.0
https://github.com/zero88/jooqx/pull/232[#232]
(https://github.com/apps/renovate[renovate[bot]])
* fix(deps): update agroal.jdk11 to v2.4 (minor)
https://github.com/zero88/jooqx/pull/231[#231]
(https://github.com/apps/renovate[renovate[bot]])
* fix(deps): adapt postgres test on jOOQ@3.19.8
https://github.com/zero88/jooqx/pull/230[#230]
(https://github.com/zero88[zero88])
* fix(deps): update vertx to v4.5.8 (minor)
https://github.com/zero88/jooqx/pull/226[#226]
(https://github.com/apps/renovate[renovate[bot]])
* fix(deps): update dependency ch.qos.logback:logback-classic to v1.5.6
https://github.com/zero88/jooqx/pull/224[#224]
(https://github.com/zero88[zero88])
* fix(deps): update testcontainers-java monorepo to v1.19.8
https://github.com/zero88/jooqx/pull/221[#221]
(https://github.com/apps/renovate[renovate[bot]])
* fix(deps): update jackson to v2.17.1
https://github.com/zero88/jooqx/pull/220[#220]
(https://github.com/apps/renovate[renovate[bot]])
* fix(deps): update dependency org.xerial:sqlite-jdbc to v3.45.3.0
https://github.com/zero88/jooqx/pull/219[#219]
(https://github.com/apps/renovate[renovate[bot]])
* chore(deps): update dependency nu.studer.jooq to v5.2.2
https://github.com/zero88/jooqx/pull/218[#218]
(https://github.com/apps/renovate[renovate[bot]])
* Feature/java17 baseline https://github.com/zero88/jooqx/pull/217[#217]
(https://github.com/zero88[zero88])
* fix(deps): update slf4j monorepo to v2.0.13
https://github.com/zero88/jooqx/pull/214[#214]
(https://github.com/apps/renovate[renovate[bot]])
* fix(deps): update dependency jacoco to v0.8.12
https://github.com/zero88/jooqx/pull/213[#213]
(https://github.com/apps/renovate[renovate[bot]])
* Improvement/reogranize project
https://github.com/zero88/jooqx/pull/212[#212]
(https://github.com/zero88[zero88])
* fix(deps): update mutinylibs.version.mutiny to v2.30.1
https://github.com/zero88/jooqx/pull/205[#205]
(https://github.com/apps/renovate[renovate[bot]])
* Renovate/logback https://github.com/zero88/jooqx/pull/203[#203]
(https://github.com/zero88[zero88])
* fix(deps): update junit5 monorepo to v5.10.2
https://github.com/zero88/jooqx/pull/202[#202]
(https://github.com/apps/renovate[renovate[bot]])
* Improvement/enable sonar step
https://github.com/zero88/jooqx/pull/201[#201]
(https://github.com/zero88[zero88])
* fix(deps): update log4j2 monorepo to v2.23.1
https://github.com/zero88/jooqx/pull/200[#200]
(https://github.com/apps/renovate[renovate[bot]])
* fix(deps): update jacksonlibs.version.jackson to v2.17.0
https://github.com/zero88/jooqx/pull/199[#199]
(https://github.com/apps/renovate[renovate[bot]])
* fix(deps): update slf4j monorepo to v2 (major)
https://github.com/zero88/jooqx/pull/198[#198]
(https://github.com/apps/renovate[renovate[bot]])
* fix(deps): update dependency org.jetbrains:annotations to v24
https://github.com/zero88/jooqx/pull/197[#197]
(https://github.com/apps/renovate[renovate[bot]])
* fix(deps): update testcontainers-java monorepo to v1.19.7
https://github.com/zero88/jooqx/pull/196[#196]
(https://github.com/apps/renovate[renovate[bot]])
* chore(build-analysis): add matrix step in build.gradle.kts
https://github.com/zero88/jooqx/pull/195[#195]
(https://github.com/zero88[zero88])
* fix(deps): update dependency org.xerial:sqlite-jdbc to v3.45.2.0
https://github.com/zero88/jooqx/pull/194[#194]
(https://github.com/apps/renovate[renovate[bot]])
* fix(deps): update dependency org.postgresql:postgresql to v42.7.3
https://github.com/zero88/jooqx/pull/193[#193]
(https://github.com/apps/renovate[renovate[bot]])
* fix(deps): update dependency org.hsqldb:hsqldb to v2.7.2
https://github.com/zero88/jooqx/pull/192[#192]
(https://github.com/apps/renovate[renovate[bot]])
* fix(deps): update dependency org.apache.derby:derby to v10.17.1.0
https://github.com/zero88/jooqx/pull/191[#191]
(https://github.com/apps/renovate[renovate[bot]])
* fix(deps): update dependency com.mchange:c3p0 to v0.10.0
https://github.com/zero88/jooqx/pull/189[#189]
(https://github.com/apps/renovate[renovate[bot]])
* chore(build): use shared-ghactions in `+build+` GHA job
https://github.com/zero88/jooqx/pull/188[#188]
(https://github.com/zero88[zero88])
* fix(deps): update dependency ch.qos.logback:logback-classic to v1.5.3
https://github.com/zero88/jooqx/pull/187[#187]
(https://github.com/apps/renovate[renovate[bot]])
* fix(deps): update databaselibs.version.agroal to v1.18
https://github.com/zero88/jooqx/pull/186[#186]
(https://github.com/apps/renovate[renovate[bot]])
* fix(deps): update dependency mysql:mysql-connector-java to v8.0.33
https://github.com/zero88/jooqx/pull/184[#184]
(https://github.com/apps/renovate[renovate[bot]])
* fix(deps): update dependency com.zaxxer:hikaricp to v4.0.3
https://github.com/zero88/jooqx/pull/183[#183]
(https://github.com/apps/renovate[renovate[bot]])
* chore: Configure Renovate
https://github.com/zero88/jooqx/pull/182[#182]
(https://github.com/apps/renovate[renovate[bot]])
* chore(build): use shared-ghactions
https://github.com/zero88/jooqx/pull/181[#181]
(https://github.com/zero88[zero88])
* Feature/upgrade GitHub action
https://github.com/zero88/jooqx/pull/180[#180]
(https://github.com/zero88[zero88])
* chore(build): use shared-ghactions
https://github.com/zero88/jooqx/pull/179[#179]
(https://github.com/zero88[zero88])
* Bump softprops/action-gh-release from 1 to 2
https://github.com/zero88/jooqx/pull/176[#176]
(https://github.com/apps/dependabot[dependabot[bot]])
* Bump crazy-max/ghaction-import-gpg from 5 to 6
https://github.com/zero88/jooqx/pull/172[#172]
(https://github.com/apps/dependabot[dependabot[bot]])
* Bump actions/setup-java from 3.11.0 to 4.0.0
https://github.com/zero88/jooqx/pull/171[#171]
(https://github.com/apps/dependabot[dependabot[bot]])
* Bump actions/setup-node from 3 to 4
https://github.com/zero88/jooqx/pull/170[#170]
(https://github.com/apps/dependabot[dependabot[bot]])
* Bump actions/checkout from 3 to 4
https://github.com/zero88/jooqx/pull/169[#169]
(https://github.com/apps/dependabot[dependabot[bot]])
* Bump actions/cache from 3 to 4
https://github.com/zero88/jooqx/pull/168[#168]
(https://github.com/apps/dependabot[dependabot[bot]])
* Update wfd-docs.yml https://github.com/zero88/jooqx/pull/167[#167]
(https://github.com/zero88[zero88])
* Feature/upgrade gradle n plugins
https://github.com/zero88/jooqx/pull/166[#166]
(https://github.com/zero88[zero88])
* Feature/use gradle plugin
https://github.com/zero88/jooqx/pull/165[#165]
(https://github.com/zero88[zero88])
* Bump actions/setup-java from 3.9.0 to 3.11.0
https://github.com/zero88/jooqx/pull/164[#164]
(https://github.com/apps/dependabot[dependabot[bot]])
* Feature/use internal vertx logger
https://github.com/zero88/jooqx/pull/161[#161]
(https://github.com/zero88[zero88])
* Bump actions/setup-java from 3.4.1 to 3.9.0
https://github.com/zero88/jooqx/pull/157[#157]
(https://github.com/apps/dependabot[dependabot[bot]])
* [noIssue][gha] replace deprecated issue
https://github.com/zero88/jooqx/pull/156[#156]
(https://github.com/zero88[zero88])
* Feature/add dml shortcut
https://github.com/zero88/jooqx/pull/155[#155]
(https://github.com/zero88[zero88])

=== https://github.com/zero88/jooqx/tree/docs/jooqx/v2.0.0-rc2+2[docs/jooqx/v2.0.0-rc2+2] (2024-06-22)

https://github.com/zero88/jooqx/compare/docs/jooqx/v2.0.0-rc2...docs/jooqx/v2.0.0-rc2+2[Full
Changelog]

=== https://github.com/zero88/jooqx/tree/docs/jooqx/v2.0.0-rc2[docs/jooqx/v2.0.0-rc2] (2024-06-21)

https://github.com/zero88/jooqx/compare/v2.0.0-rc.1...docs/jooqx/v2.0.0-rc2[Full
Changelog]

*Implemented enhancements:*

* Support jooq 3.19.* https://github.com/zero88/jooqx/issues/174[#174]

*Fixed bugs:*

* DataTypeMapper does not work correctly since jOOQ3.18
https://github.com/zero88/jooqx/issues/235[#235]

=== https://github.com/zero88/jooqx/tree/v2.0.0-rc.1[v2.0.0-rc.1] (2024-03-16)

https://github.com/zero88/jooqx/compare/docs/jooqx/v2.0.0-rc1...v2.0.0-rc.1[Full
Changelog]

*Implemented enhancements:*

* Add DML shortcut https://github.com/zero88/jooqx/issues/154[#154]

=== https://github.com/zero88/jooqx/tree/docs/jooqx/v2.0.0-rc1[docs/jooqx/v2.0.0-rc1] (2023-01-11)

https://github.com/zero88/jooqx/compare/v2.0.0-rc1...docs/jooqx/v2.0.0-rc1[Full
Changelog]

=== https://github.com/zero88/jooqx/tree/v2.0.0-rc1[v2.0.0-rc1] (2023-01-11)

https://github.com/zero88/jooqx/compare/v1.0.0...v2.0.0-rc1[Full
Changelog]

*Breaking changes:*

* Move SQLResultAdapter is close to RowDecoder
https://github.com/zero88/jooqx/issues/115[#115]
* Breaking change to jooqx v2
https://github.com/zero88/jooqx/issues/101[#101]
* JSON serialization SPI https://github.com/zero88/jooqx/issues/12[#12]

*Implemented enhancements:*

* Able to execute multiple statements in one connection
https://github.com/zero88/jooqx/issues/137[#137]
* Add shortcut for fetchJsonObject/fetchJsonArray
https://github.com/zero88/jooqx/issues/133[#133]
* Add shortcut for fetchOne/fetchMany/fetchExists/fetchCount into jooqx
https://github.com/zero88/jooqx/issues/129[#129]
* Refactor code generation for `+rxify+`
https://github.com/zero88/jooqx/issues/103[#103]
* Support SQL block https://github.com/zero88/jooqx/issues/98[#98]
* Support plain SQL https://github.com/zero88/jooqx/issues/97[#97]
* Support mutiny https://github.com/zero88/jooqx/issues/83[#83]
* Support Rx3 https://github.com/zero88/jooqx/issues/82[#82]
* Remove lombok dependency
https://github.com/zero88/jooqx/issues/65[#65]
* Support DDL https://github.com/zero88/jooqx/issues/51[#51]
* Introduce jooqx SPI provider
https://github.com/zero88/jooqx/issues/49[#49]
* Rxify for JooqxBuilder https://github.com/zero88/jooqx/issues/38[#38]
* Support plain JDBC in Vertx reactive mode
https://github.com/zero88/jooqx/issues/33[#33]
* Support SQL Procedure https://github.com/zero88/jooqx/issues/25[#25]
* Integrate with RQL https://github.com/zero88/jooqx/issues/8[#8]

*Fixed bugs:*

* MySQL select count https://github.com/zero88/jooqx/issues/124[#124]
* Unable convert data by Select
https://github.com/zero88/jooqx/issues/107[#107]
* Wrong jooqx-core-test-fixtures on Nexus
https://github.com/zero88/jooqx/issues/53[#53]

*Closed issues:*

* vertx-junit5 > 4.2.5 always failed to open SQL connection
https://github.com/zero88/jooqx/issues/146[#146]

*Merged pull requests:*

* Docs/minor update https://github.com/zero88/jooqx/pull/152[#152]
(https://github.com/zero88[zero88])
* [gradle] Upgrade vertx-4.3.5
https://github.com/zero88/jooqx/pull/149[#149]
(https://github.com/zero88[zero88])
* [#146] Upgrade version of lib dependencies
https://github.com/zero88/jooqx/pull/147[#147]
(https://github.com/zero88[zero88])
* Update doc for release 2.0.0-rc1
https://github.com/zero88/jooqx/pull/145[#145]
(https://github.com/zero88[zero88])
* [ci] Add changelog generator
https://github.com/zero88/jooqx/pull/142[#142]
(https://github.com/zero88[zero88])
* Implement JooqxSession https://github.com/zero88/jooqx/pull/138[#138]
(https://github.com/zero88[zero88])
* Feature/support block sql statement
https://github.com/zero88/jooqx/pull/135[#135]
(https://github.com/zero88[zero88])
* Feature/add shortcut for fetch json
https://github.com/zero88/jooqx/pull/134[#134]
(https://github.com/zero88[zero88])
* Feature/introduce collector by sql result adapter
https://github.com/zero88/jooqx/pull/131[#131]
(https://github.com/zero88[zero88])
* Feature/refactor sql result adapter
https://github.com/zero88/jooqx/pull/128[#128]
(https://github.com/zero88[zero88])
* Feature/procedure https://github.com/zero88/jooqx/pull/123[#123]
(https://github.com/zero88[zero88])
* Improvement/stablize test
https://github.com/zero88/jooqx/pull/122[#122]
(https://github.com/zero88[zero88])
* Feature/add reactivex generator
https://github.com/zero88/jooqx/pull/113[#113]
(https://github.com/zero88[zero88])
* breaking-change-to-v2 https://github.com/zero88/jooqx/pull/102[#102]
(https://github.com/zero88[zero88])
* Support plain SQL https://github.com/zero88/jooqx/pull/100[#100]
(https://github.com/zero88[zero88])
* Feature/add rxify builder https://github.com/zero88/jooqx/pull/95[#95]
(https://github.com/zero88[zero88])
* Feature/remove lombok https://github.com/zero88/jooqx/pull/92[#92]
(https://github.com/zero88[zero88])
* Feature/add documentation branch
https://github.com/zero88/jooqx/pull/86[#86]
(https://github.com/zero88[zero88])
* Remove lombok in jpa-ext https://github.com/zero88/jooqx/pull/84[#84]
(https://github.com/zero88[zero88])
* Feature/remove lombok in rsql
https://github.com/zero88/jooqx/pull/68[#68]
(https://github.com/zero88[zero88])
* Feature/upgrade project deps
https://github.com/zero88/jooqx/pull/64[#64]
(https://github.com/zero88[zero88])
* Feature/merge with rsql project
https://github.com/zero88/jooqx/pull/62[#62]
(https://github.com/zero88[zero88])
* Feature/support ddl https://github.com/zero88/jooqx/pull/52[#52]
(https://github.com/zero88[zero88])
* Feature/spi provider https://github.com/zero88/jooqx/pull/50[#50]
(https://github.com/zero88[zero88])

=== https://github.com/zero88/jooqx/tree/v1.0.0[1.0.0]

https://github.com/zero88/jooqx/compare/f7e4efadba4209f4b39548e08bf60ba814e4c6bb...HEAD[Full
Changelog]

*Closed issues:*

* Document & usage https://github.com/zero88/jooqx/issues/24[#24]
* Vertx gen to Rxify https://github.com/zero88/jooqx/issues/18[#18]
* Test with complex query that return join result to ensure
VertxJooqRecord can handle
https://github.com/zero88/jooqx/issues/11[#11]
* Add some useful basic SQL query as DAO function
https://github.com/zero88/jooqx/issues/10[#10]
* Convert result from VertxJooqRecord to Table record or Table pojo
https://github.com/zero88/jooqx/issues/9[#9]
* Support SQL transaction https://github.com/zero88/jooqx/issues/7[#7]
* Data type converter between Vertx SQL and jOOQ
https://github.com/zero88/jooqx/issues/6[#6]
* Error handling https://github.com/zero88/jooqx/issues/5[#5]
* Support batch DML https://github.com/zero88/jooqx/issues/3[#3]

*Merged pull requests:*

* Feature/rxify v2 https://github.com/zero88/jooqx/pull/34[#34]
(https://github.com/zero88[zero88])
* Vert.x jOOQ Data converter
https://github.com/zero88/jooqx/pull/32[#32]
(https://github.com/zero88[zero88])
* Improve/api-2-document https://github.com/zero88/jooqx/pull/30[#30]
(https://github.com/zero88[zero88])
* Feature/docs https://github.com/zero88/jooqx/pull/28[#28]
(https://github.com/zero88[zero88])
* Feature/transaction https://github.com/zero88/jooqx/pull/21[#21]
(https://github.com/zero88[zero88])
* Feature/complex query https://github.com/zero88/jooqx/pull/19[#19]
(https://github.com/zero88[zero88])
* Feature/common dsl https://github.com/zero88/jooqx/pull/17[#17]
(https://github.com/zero88[zero88])
* Feature/error handling https://github.com/zero88/jooqx/pull/16[#16]
(https://github.com/zero88[zero88])
* Feature/support batch https://github.com/zero88/jooqx/pull/15[#15]
(https://github.com/zero88[zero88])
* Bump actions/cache from v2 to v2.1.4
https://github.com/zero88/jooqx/pull/14[#14]
(https://github.com/apps/dependabot[dependabot[bot]])
* Bump zero88/gh-project-context from v1.0.0 to v1.0.3
https://github.com/zero88/jooqx/pull/2[#2]
(https://github.com/apps/dependabot[dependabot[bot]])
* Bump actions/cache from v2.1.3 to v2.1.4
https://github.com/zero88/jooqx/pull/1[#1]
(https://github.com/apps/dependabot[dependabot[bot]])

_This Changelog was automatically generated by
https://github.com/github-changelog-generator/github-changelog-generator[github_changelog_generator]_

* _This Changelog was automatically generated by
https://github.com/github-changelog-generator/github-changelog-generator[github_changelog_generator]_
