== Changelog

=== https://github.com/zero88/jooqx/tree/v2.0.0-rc1[v2.0.0-rc1] (2023-01-11)

https://github.com/zero88/jooqx/compare/v1.0.0...v2.0.0-rc1[Full
Changelog]

*Breaking changes:*

* Move SQLResultAdapter is close to RowDecoder
https://github.com/zero88/jooqx/issues/115[#115]
* Breaking change to jooqx v2
https://github.com/zero88/jooqx/issues/101[#101]
* JSON serialization SPI https://github.com/zero88/jooqx/issues/12[#12]

*Implemented enhancements:*

* Able to execute multiple statements in one connection
https://github.com/zero88/jooqx/issues/137[#137]
* Add shortcut for fetchJsonObject/fetchJsonArray
https://github.com/zero88/jooqx/issues/133[#133]
* Add shortcut for fetchOne/fetchMany/fetchExists/fetchCount into jooqx
https://github.com/zero88/jooqx/issues/129[#129]
* Refactor code generation for `+rxify+`
https://github.com/zero88/jooqx/issues/103[#103]
* Support SQL block https://github.com/zero88/jooqx/issues/98[#98]
* Support plain SQL https://github.com/zero88/jooqx/issues/97[#97]
* Support mutiny https://github.com/zero88/jooqx/issues/83[#83]
* Support Rx3 https://github.com/zero88/jooqx/issues/82[#82]
* Remove lombok dependency
https://github.com/zero88/jooqx/issues/65[#65]
* Support DDL https://github.com/zero88/jooqx/issues/51[#51]
* Introduce jooqx SPI provider
https://github.com/zero88/jooqx/issues/49[#49]
* Rxify for JooqxBuilder https://github.com/zero88/jooqx/issues/38[#38]
* Support plain JDBC in Vertx reactive mode
https://github.com/zero88/jooqx/issues/33[#33]
* Support SQL Procedure https://github.com/zero88/jooqx/issues/25[#25]
* Integrate with RQL https://github.com/zero88/jooqx/issues/8[#8]

*Fixed bugs:*

* MySQL select count https://github.com/zero88/jooqx/issues/124[#124]
* Unable convert data by Select
https://github.com/zero88/jooqx/issues/107[#107]
* Wrong jooqx-core-test-fixtures on Nexus
https://github.com/zero88/jooqx/issues/53[#53]

*Closed issues:*

* vertx-junit5 > 4.2.5 always failed to open SQL connection
https://github.com/zero88/jooqx/issues/146[#146]

*Merged pull requests:*

* Docs/minor update https://github.com/zero88/jooqx/pull/152[#152]
(https://github.com/zero88[zero88])
* [gradle] Upgrade vertx-4.3.5
https://github.com/zero88/jooqx/pull/149[#149]
(https://github.com/zero88[zero88])
* [#146] Upgrade version of lib dependencies
https://github.com/zero88/jooqx/pull/147[#147]
(https://github.com/zero88[zero88])
* Update doc for release 2.0.0-rc1
https://github.com/zero88/jooqx/pull/145[#145]
(https://github.com/zero88[zero88])
* [ci] Add changelog generator
https://github.com/zero88/jooqx/pull/142[#142]
(https://github.com/zero88[zero88])
* Implement JooqxSession https://github.com/zero88/jooqx/pull/138[#138]
(https://github.com/zero88[zero88])
* Feature/support block sql statement
https://github.com/zero88/jooqx/pull/135[#135]
(https://github.com/zero88[zero88])
* Feature/add shortcut for fetch json
https://github.com/zero88/jooqx/pull/134[#134]
(https://github.com/zero88[zero88])
* Feature/introduce collector by sql result adapter
https://github.com/zero88/jooqx/pull/131[#131]
(https://github.com/zero88[zero88])
* Feature/refactor sql result adapter
https://github.com/zero88/jooqx/pull/128[#128]
(https://github.com/zero88[zero88])
* Feature/procedure https://github.com/zero88/jooqx/pull/123[#123]
(https://github.com/zero88[zero88])
* Improvement/stablize test
https://github.com/zero88/jooqx/pull/122[#122]
(https://github.com/zero88[zero88])
* Feature/add reactivex generator
https://github.com/zero88/jooqx/pull/113[#113]
(https://github.com/zero88[zero88])
* breaking-change-to-v2 https://github.com/zero88/jooqx/pull/102[#102]
(https://github.com/zero88[zero88])
* Support plain SQL https://github.com/zero88/jooqx/pull/100[#100]
(https://github.com/zero88[zero88])
* Feature/add rxify builder https://github.com/zero88/jooqx/pull/95[#95]
(https://github.com/zero88[zero88])
* Feature/remove lombok https://github.com/zero88/jooqx/pull/92[#92]
(https://github.com/zero88[zero88])
* Feature/add documentation branch
https://github.com/zero88/jooqx/pull/86[#86]
(https://github.com/zero88[zero88])
* Remove lombok in jpa-ext https://github.com/zero88/jooqx/pull/84[#84]
(https://github.com/zero88[zero88])
* Feature/remove lombok in rsql
https://github.com/zero88/jooqx/pull/68[#68]
(https://github.com/zero88[zero88])
* Feature/upgrade project deps
https://github.com/zero88/jooqx/pull/64[#64]
(https://github.com/zero88[zero88])
* Feature/merge with rsql project
https://github.com/zero88/jooqx/pull/62[#62]
(https://github.com/zero88[zero88])
* Feature/support ddl https://github.com/zero88/jooqx/pull/52[#52]
(https://github.com/zero88[zero88])
* Feature/spi provider https://github.com/zero88/jooqx/pull/50[#50]
(https://github.com/zero88[zero88])

=== https://github.com/zero88/jooqx/tree/v1.0.0[1.0.0]

https://github.com/zero88/jooqx/compare/f7e4efadba4209f4b39548e08bf60ba814e4c6bb...HEAD[Full
Changelog]

*Closed issues:*

* Document & usage https://github.com/zero88/jooqx/issues/24[#24]
* Vertx gen to Rxify https://github.com/zero88/jooqx/issues/18[#18]
* Test with complex query that return join result to ensure
VertxJooqRecord can handle
https://github.com/zero88/jooqx/issues/11[#11]
* Add some useful basic SQL query as DAO function
https://github.com/zero88/jooqx/issues/10[#10]
* Convert result from VertxJooqRecord to Table record or Table pojo
https://github.com/zero88/jooqx/issues/9[#9]
* Support SQL transaction https://github.com/zero88/jooqx/issues/7[#7]
* Data type converter between Vertx SQL and jOOQ
https://github.com/zero88/jooqx/issues/6[#6]
* Error handling https://github.com/zero88/jooqx/issues/5[#5]
* Support batch DML https://github.com/zero88/jooqx/issues/3[#3]

*Merged pull requests:*

* Feature/rxify v2 https://github.com/zero88/jooqx/pull/34[#34]
(https://github.com/zero88[zero88])
* Vert.x jOOQ Data converter
https://github.com/zero88/jooqx/pull/32[#32]
(https://github.com/zero88[zero88])
* Improve/api-2-document https://github.com/zero88/jooqx/pull/30[#30]
(https://github.com/zero88[zero88])
* Feature/docs https://github.com/zero88/jooqx/pull/28[#28]
(https://github.com/zero88[zero88])
* Feature/transaction https://github.com/zero88/jooqx/pull/21[#21]
(https://github.com/zero88[zero88])
* Feature/complex query https://github.com/zero88/jooqx/pull/19[#19]
(https://github.com/zero88[zero88])
* Feature/common dsl https://github.com/zero88/jooqx/pull/17[#17]
(https://github.com/zero88[zero88])
* Feature/error handling https://github.com/zero88/jooqx/pull/16[#16]
(https://github.com/zero88[zero88])
* Feature/support batch https://github.com/zero88/jooqx/pull/15[#15]
(https://github.com/zero88[zero88])
* Bump actions/cache from v2 to v2.1.4
https://github.com/zero88/jooqx/pull/14[#14]
(https://github.com/apps/dependabot[dependabot[bot]])
* Bump zero88/gh-project-context from v1.0.0 to v1.0.3
https://github.com/zero88/jooqx/pull/2[#2]
(https://github.com/apps/dependabot[dependabot[bot]])
* Bump actions/cache from v2.1.3 to v2.1.4
https://github.com/zero88/jooqx/pull/1[#1]
(https://github.com/apps/dependabot[dependabot[bot]])

_This Changelog was automatically generated by
https://github.com/github-changelog-generator/github-changelog-generator[github_changelog_generator]_
