package io.github.zero88.jooqx.resultadapter;

import java.util.Collections;
import java.util.List;

import org.jooq.InsertResultStep;
import org.jooq.Record;
import org.jooq.SelectForUpdateStep;
import org.jooq.SelectWhereStep;

import io.github.zero88.jooqx.DSLAdapter;
import io.github.zero88.jooqx.Jooqx;
import io.github.zero88.jooqx.JsonRecord;
import io.github.zero88.sample.model.pgsql.Tables;
import io.github.zero88.sample.model.pgsql.tables.Books;
import io.github.zero88.sample.model.pgsql.tables.pojos.Authors;
import io.github.zero88.sample.model.pgsql.tables.records.AuthorsRecord;
import io.github.zero88.sample.model.pgsql.tables.records.BooksRecord;
import io.vertx.docgen.Source;

@Source
class ExampleResultAdapter {

    // @formatter:off
    void toJsonRecord(Jooqx jooqx) {
        /*
         * Vertx JsonObject vs jOOQ Record... Ya, merging: JsonRecord
         */
        SelectForUpdateStep<AuthorsRecord> q = jooqx.dsl()
                                                    .selectFrom(Tables.AUTHORS)
                                                    .where(Tables.AUTHORS.NAME.eq("zero88"))
                                                    .limit(1)
                                                    .offset(1);
        jooqx.execute(q, DSLAdapter.fetchJsonRecord(q.asTable()))   // <1>
             .onSuccess(r -> {
                JsonRecord<?> record = r;                           // <2>
                System.out.println(record.toJson());                // <3>
             });
    }
    // @formatter:on

    void toTableRecord(Jooqx jooqx) {
        SelectWhereStep<AuthorsRecord> query = jooqx.dsl().selectFrom(Tables.AUTHORS);
        // Authors is POJO class that generated by jOOQ
        jooqx.execute(query, DSLAdapter.fetchMany(Tables.AUTHORS, Authors.class), ar -> {
            List<Authors> authors = ar.result();
            Authors author = authors.get(0);
            System.out.println(author.getId());                 //  output: 1
            System.out.println(author.getCountry());            //  output: UK
        });
    }

    void toFields(Jooqx jooqx) {
        Books table = Tables.BOOKS;
        InsertResultStep<BooksRecord> insert = jooqx.dsl().insertInto(table, table.TITLE).values("aha").returning();
        jooqx.execute(insert, DSLAdapter.fetchOne(table, Collections.singletonList(table.ID)), ar -> {
            Record record = ar.result();
            System.out.println(record.getValue(0));
        });
    }

}
