name: docs

on:
  push:
    branches: [ docs ]
    tags: [ 'docs/v*' ]
    paths-ignore:
      - '.github/ISSUE_TEMPLATE/**'
      - '.github/*.yml'
      - '*.md'
      - 'LICENSE'
  pull_request:
    types: [ opened, synchronize, reopened, closed ]
    branches: [ docs ]
    paths-ignore:
      - '.github/ISSUE_TEMPLATE/**'
      - '.github/*.yml'
      - '*.md'
      - 'LICENSE'

jobs:
  context:
    runs-on: ubuntu-latest
    outputs:
      branch: ${{ steps.context.outputs.branch }}
      shouldBuild: ${{ steps.context.outputs.shouldBuild }}
      shouldPublish: ${{ steps.context.outputs.shouldPublish }}
      isRelease: ${{ steps.context.outputs.isRelease }}
      version: ${{ steps.context.outputs.version }}
      semanticVersion: ${{ steps.context.outputs.semanticVersion }}
      commitId: ${{ steps.context.outputs.commitId }}

    steps:
      - uses: actions/checkout@v2.4.0
        with:
          token: ${{ secrets.OSS_GITHUB_TOKEN }}

      - name: Query project context
        id: context
        uses: ./.github/actions/gha-context
        with:
          gpgKey: ${{ secrets.CI_GPG_PRIVATE_KEY }}
          gpgPassphrase: ${{ secrets.CI_GPG_PASSPHARSE }}
