name: jooqx

on:
  push:
    branches: [ main ]
    tags: [ 'v*' ]
    paths-ignore:
      - '.github/ISSUE_TEMPLATE/**'
      - '.github/*.yml'
      - '*.md'
      - 'LICENSE'
  pull_request:
    types: [ opened, synchronize, reopened, closed ]
    branches: [ main ]
    paths-ignore:
      - '.github/ISSUE_TEMPLATE/**'
      - '.github/*.yml'
      - '*.md'
      - 'LICENSE'

env:
  PROFILE: 'jooqx'
  JAVA_DIST: 'temurin'

jobs:
  context:
    runs-on: ubuntu-latest
    outputs:
      branch: ${{ steps.context.outputs.branch }}
      shouldBuild: ${{ steps.verify.outputs.shouldBuild }}
      shouldPublish: ${{ steps.verify.outputs.shouldPublish }}
      isRelease: ${{ steps.context.outputs.isRelease }}
      version: ${{ steps.context.outputs.version }}
      semanticVersion: ${{ steps.context.outputs.semanticVersion }}
      commitId: ${{ steps.context.outputs.commitId }}

    steps:
      - uses: actions/checkout@v2.4.0
        with:
          token: ${{ secrets.OSS_GITHUB_TOKEN }}

      - name: Query project context
        id: context
        uses: ./.github/actions/gha-context
        with:
          profile: ${{ env.PROFILE }}
          gpgKey: ${{ secrets.CI_GPG_PRIVATE_KEY }}
          gpgPassphrase: ${{ secrets.CI_GPG_PASSPHARSE }}

      - name: Verify rsql/jpa release branch
        id: verify
        shell: bash
        run: |
          if [[ "${{ steps.context.outputs.branch }}" =~ ^(jpa|rsql)/.* ]]; then
            echo ::set-output name=shouldBuild::false
            echo ::set-output name=shouldPublish::false
          else
            echo ::set-output name=shouldBuild::${{ steps.context.outputs.shouldBuild }}
            echo ::set-output name=shouldPublish::${{ steps.context.outputs.shouldPublish }}
          fi

  build:
    needs: context
    if: needs.context.outputs.shouldBuild == 'true'
    strategy:
      matrix:
        java: [ '8', '11' ]
        os: [ 'ubuntu-latest', 'windows-latest' ]
    name: Java ${{ matrix.Java }} (${{ matrix.os }}) build
    runs-on: ${{ matrix.os }}
    env:
      PROFILE: 'ciBuild'
    steps:
      - uses: actions/checkout@v2.4.0

      - name: Build
        uses: ./.github/actions/gha-build
        with:
          profile: ${{ env.PROFILE }}
          version: ${{ needs.context.outputs.version }}
          semanticVersion: ${{ needs.context.outputs.semanticVersion }}
          hashVersion: ${{ needs.context.outputs.commitId }}
          javaDist: ${{ env.JAVA_DIST }}
          javaVersion: ${{ matrix.Java }}

  analysis:
    needs: context
    if: needs.context.outputs.shouldBuild == 'true'
    strategy:
      matrix:
        java: [ '11' ]
        os: [ 'ubuntu-latest' ]
    name: Java ${{ matrix.Java }} (${{ matrix.os }}) test
    runs-on: ${{ matrix.os }}
    env:
      PROFILE: 'ciSonar'
    steps:
      - uses: actions/checkout@v2.4.0
        with:
          fetch-depth: 0

      - uses: actions/setup-java@v2
        with:
          distribution: ${{ env.JAVA_DIST }}
          java-version: ${{ matrix.Java }}
          cache: 'gradle'

      - name: Cache SonarCloud packages
        uses: actions/cache@v2.1.4
        with:
          path: ~/.sonar/cache
          key: ${{ runner.os }}-sonar
          restore-keys: ${{ runner.os }}-sonar

      - name: Generate jOOQ test schema
        shell: bash
        run: ./generateJooq.sh

      - name: Full test
        shell: bash
        run: |
          ./gradlew test --stacktrace \
              -Pprofile=${{ env.PROFILE }} \
              -PsemanticVersion=${{ needs.context.outputs.semanticVersion }}

      - name: SonarQube
        shell: bash
        run: |
          ./gradlew sonarqube -x test --stacktrace \
              -Pprofile=${{ env.PROFILE }} \
              -PsemanticVersion=${{ needs.context.outputs.semanticVersion }} \
              -Dsonar.branch.name=${{ needs.context.outputs.branch }} \
              -Dsonar.login=${{ secrets.OSS_SONARQUBE_TOKEN }} \
              -Dorg.gradle.jvmargs="-Xmx2g -XX:MaxMetaspaceSize=512m -XX:+HeapDumpOnOutOfMemoryError"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  publish:
    runs-on: ubuntu-latest
    needs: [ context, build, analysis ]
    if: needs.context.outputs.shouldPublish == 'true' || needs.context.outputs.isRelease == 'true'
    steps:
      - uses: actions/checkout@v2.4.0

      - name: Publish artifact to remote registry
        uses: ./.github/actions/gha-publish
        with:
          profile: ${{ env.PROFILE }}
          version: ${{ needs.context.outputs.version }}
          semanticVersion: ${{ needs.context.outputs.semanticVersion }}
          hashVersion: ${{ needs.context.outputs.commitId }}
          isRelease: ${{ needs.context.outputs.isRelease }}
          githubToken: ${{ secrets.GITHUB_TOKEN }}
          ossrhUser: ${{ secrets.OSS_SONATYPE_USER }}
          ossrhToken: ${{ secrets.OSS_SONATYPE_PASSWORD }}
          gpgKey: ${{ secrets.CI_GPG_PRIVATE_KEY }}
          gpgPassphrase: ${{ secrets.CI_GPG_PASSPHARSE }}

  docs:
    runs-on: ubuntu-latest
    needs: [ context, build ]
    if: needs.context.outputs.shouldPublish == 'true' || needs.context.outputs.isRelease == 'true'
    steps:
      - uses: actions/checkout@v2.4.0
        with:
          token: ${{ secrets.OSS_GITHUB_TOKEN }}

      - name: Build documentation
        uses: ./.github/actions/gha-docs
        with:
          profile: ${{ env.PROFILE }}
          version: ${{ needs.context.outputs.version }}
          hashVersion: ${{ needs.context.outputs.commitId }}
          isRelease: ${{ needs.context.outputs.isRelease }}
          gpgKey: ${{ secrets.CI_GPG_PRIVATE_KEY }}
          gpgPassphrase: ${{ secrets.CI_GPG_PASSPHARSE }}

  release:
    runs-on: ubuntu-latest
    needs: [ context, build, analysis, publish ]
    if: needs.context.outputs.isRelease == 'true'
    steps:
      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          name: Release ${{ env.PROFILE }} ${{ needs.context.outputs.version }}
          tag_name: ${{ needs.context.outputs.branch }}
          generate_release_notes: true
