name: jpa

on:
  push:
    branches: [ main ]
    tags: [ 'v*' ]
    paths:
      - 'jpa-ext/**'
      - '.github/workflows/jpa.yml'
      - '.github/actions/*.yml'
  pull_request:
    types: [ opened, synchronize, reopened, closed ]
    branches: [ main ]
    paths:
      - 'jpa-ext/**'
      - '.github/workflows/jpa.yml'
      - '.github/actions/*.yml'

env:
  PROFILE: jpa

jobs:
  context:
    runs-on: ubuntu-latest
    outputs:
      branch: ${{ steps.context.outputs.branch }}
      shouldBuild: ${{ steps.context.outputs.shouldBuild }}
      shouldPublish: ${{ steps.context.outputs.shouldPublish }}
      isRelease: ${{ steps.context.outputs.isRelease }}
      version: ${{ steps.context.outputs.version }}
      semanticVersion: ${{ steps.context.outputs.semanticVersion }}
      commitId: ${{ steps.context.outputs.commitId }}

    steps:
      - uses: actions/checkout@v2.4.0
        with:
          token: ${{ secrets.OSS_GITHUB_TOKEN }}

      - name: Query project context
        id: context
        uses: ./.github/actions/gha-context
        with:
          gpgKey: ${{ secrets.CI_GPG_PRIVATE_KEY }}
          gpgPassphrase: ${{ secrets.CI_GPG_PASSPHARSE }}

  build:
    runs-on: ubuntu-latest
    needs: context
    if: needs.context.outputs.shouldBuild == 'true'
    strategy:
      matrix:
        java: [ '8', '11' ]
        os: [ 'ubuntu-latest', 'windows-latest' ]
    steps:
      - uses: actions/checkout@v2.4.0

      - name: Build
        uses: ./.github/actions/gha-build
        with:
          profile: ${{ env.PROFILE }}
          version: ${{ needs.context.outputs.version }}
          semanticVersion: ${{ needs.context.outputs.semanticVersion }}
          hashVersion: ${{ needs.context.outputs.commitId }}
          javaVersion: ${{ matrix.Java }}

      - name: Test
        shell: bash
        run: ./gradlew test -Pprofile=${{ env.PROFILE }}

  publish:
    runs-on: ubuntu-latest
    needs: [ context, build ]
    if: needs.context.outputs.shouldPublish == 'true' || needs.context.outputs.isRelease == 'true'
    steps:
      - uses: actions/checkout@v2.4.0

      - name: Release and promote artifact
        uses: ./.github/actions/gha-publish
        with:
          profile: ${{ env.PROFILE }}
          version: ${{ needs.context.outputs.version }}
          semanticVersion: ${{ needs.context.outputs.semanticVersion }}
          hashVersion: ${{ needs.context.outputs.commitId }}
          isRelease: ${{ needs.context.outputs.isRelease }}
          githubToken: ${{ secrets.GITHUB_TOKEN }}
          ossrhUser: ${{ secrets.OSS_SONATYPE_USER }}
          ossrhToken: ${{ secrets.OSS_SONATYPE_PASSWORD }}
          gpgKey: ${{ secrets.CI_GPG_PRIVATE_KEY }}
          gpgPassphrase: ${{ secrets.CI_GPG_PASSPHARSE }}

  release:
    runs-on: ubuntu-latest
    needs: [ context, build, publish ]
    if: needs.context.outputs.isRelease == 'true'
    steps:
      - name: Create GitHub Release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ inputs.githubToken }}
        with:
          tag_name: ${{ needs.context.outputs.branch }}
          release_name: Release ${{ needs.context.outputs.branch }}
