name: build-docs

on:
  workflow_dispatch:
    inputs:
      profile:
        description: 'Project profile'
        required: true
      version:
        description: 'Project version'
        required: true
      semanticVersion:
        description: 'Project semantic version'
        required: false
      hashVersion:
        description: 'Project hash commit'
        required: true
      sha:
        description: 'SHA commit id'
        required: true
      isRelease:
        description: 'Is release'
        required: false
        default: false
      antoraBuildDir:
        description: 'Specifics Antora output dir per profile'
        required: true
      javaDist:
        description: 'Java distribution'
        required: false
        default: 'temurin'
      javaVersion:
        description: 'Java version'
        required: false
        default: '17'

jobs:
  build:
    name: Build ${{ github.event.inputs.profile }} documentation
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.event.inputs.sha }}
          token: ${{ secrets.OSS_GITHUB_TOKEN }}
          fetch-depth: 0
          submodules: 'true'

      - name: Import GPG key
        uses: crazy-max/ghaction-import-gpg@v3
        with:
          git-user-signingkey: true
          git-commit-gpgsign: true
          git-tag-gpgsign: false
          git-push-gpgsign: false
          gpg-private-key: ${{ secrets.CI_GPG_PRIVATE_KEY }}
          passphrase: ${{ secrets.CI_GPG_PASSPHARSE }}

      - uses: actions/setup-java@v2
        with:
          distribution: ${{ github.event.inputs.javaDist }}
          java-version: ${{ github.event.inputs.javaVersion }}
          cache: 'gradle'

      - name: Evaluate context
        id: context
        shell: bash
        run: |
          if [[ '${{ github.event.inputs.isRelease }}' == 'true' ]]; then
            docBranch="docs/${{ github.event.inputs.profile }}/v${{ github.event.inputs.version }}"
            docVersion="${{ github.event.inputs.version }}"
            commitVersion="${{ github.event.inputs.version }}-${{ github.event.inputs.hashVersion }}"
          else
            docBranch="docs/main"
            docVersion="main"
            commitVersion="main-${{ github.event.inputs.hashVersion }}"
          fi
          docProfile="${{ github.event.inputs.profile }}:docs"
          docOutDir="./antora/${{ github.event.inputs.profile }}"
          
          echo ::set-output name=docProfile::$docProfile
          echo ::set-output name=docBranch::$docBranch
          echo ::set-output name=docVersion::$docVersion
          echo ::set-output name=docOutDir::$docOutDir
          echo ::set-output name=docBuildDir::${{ github.event.inputs.antoraBuildDir }}
          echo ::set-output name=ciMsg::"${{ github.event.inputs.profile }} documentation [$commitVersion]"

      - name: Generate jOOQ test schema
        shell: bash
        run: ./gradlew :integtest:pg:generateJooq

      - name: Build docs
        shell: bash
        run: |
          ./gradlew antora \
              -Pprofile=${{ steps.context.outputs.docProfile }} \
              -PdocVersion=${{ steps.context.outputs.docVersion }} \
              -Pversion=${{ github.event.inputs.version }} \
              -PsemanticVersion=${{ github.event.inputs.semanticVersion }} \
              -PbuildHash=${{ github.event.inputs.hashVersion }} \
              -PbuildBy="GitHub-Action"

      - name: Sync changes to Git branch [${{ steps.context.outputs.docBranch }}]
        shell: bash
        run: |
          git fetch
          git checkout docs/main
          rm -rf ${{ steps.context.outputs.docOutDir }} \
            && mkdir ${{ steps.context.outputs.docOutDir }} \
            && touch ${{ steps.context.outputs.docOutDir }}/.gitkeep \
            && cp -rf ./${{ steps.context.outputs.docBuildDir }}/* ${{ steps.context.outputs.docOutDir }}
          git add .
          git diff-index --quiet HEAD || git commit -am "Update ${{ steps.context.outputs.ciMsg }}"
          if [[ '${{ github.event.inputs.isRelease }}' == 'true' ]]; then
               git tag -sf -am "Release ${{ steps.context.outputs.ciMsg }}" ${{ steps.context.outputs.docBranch }}
          fi
          git push --follow-tags

  deploy:
    needs: build
    name: Trigger to deploy website
    runs-on: ubuntu-latest
    env:
      REPO: zero88/jooqx-webdocs
      REF: main
      WORKFLOW: docs.yml
      GITHUB_TOKEN: ${{ secrets.OSS_GITHUB_TOKEN }}
    steps:
      - name: Trigger to deploy workflow
        shell: bash
        run: |
          gh workflow run ${{ env.WORKFLOW }} \
            --repo ${{ env.REPO }} --ref ${{ env.REF }} -f ciMsg="Deploy ${{ steps.context.outputs.ciMsg }}"

      - name: Verify GitHub workflow run
        shell: bash
        run: |
          sleep 5
          fields=workflowDatabaseId,databaseId,status,event,headBranch,headSha,name,conclusion,url,createdAt,updatedAt
          gh run list -R ${{ env.REPO }} -b ${{ env.REF }} -w ${{ env.WORKFLOW }} -L 1 --json $fields | jq
